# Uncomment the next line to define a global platform for your project
platform :ios, '13.4'

target 'Droplet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Droplet

  # add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods

  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Core'

  target 'DropletTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DropletUITests' do
    # Pods for testing
  end

end
